---
apiVersion: v1
kind: Service
metadata:
  name: dubbo
  labels:
    app: dubbo-k8s
spec:
  type: NodePort
  ports:
  - nodePort: 19513
    port: 20880
    name: dubbo
  selector:
    app: dubbo-k8s
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dubbo-k8s
  namespace: default
  labels:
    k8s-app: dubbo-k8s
spec:
  strategy:
    rollingUpdate:
      maxSurge: 10%
      maxUnavailable: 0
  selector:
    matchLabels:
      k8s-app: dubbo-k8s
  template:
    metadata:
      labels:
        k8s-app: dubbo-k8s
    spec:
      containers:
      - name: dubbo
        image: hub.chinacloud.com/catalog/dubbo:2.5.7
        ports:
        - containerPort: 20880
        readinessProbe:
          tcpSocket:
            port: 20880
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: 20880
          initialDelaySeconds: 15
          periodSeconds: 20
        env:
          - name: DUBBO_IP_TO_REGISTRY
            valueFrom:
             fieldRef:
              fieldPath: status.podIP
          - name: ZK_SERVICE
            value: zookeeper-cs