apiVersion: v1
kind: ConfigMap
metadata:
  name: ceph-server-conf
  labels:
    name: ceph-server-conf
data:
  ceph.conf: |-
    [global]
    fsid = 98402dee-a8fc-4564-8522-e56ec5f2155c
    mon_initial_members = cc25, nc100, nc101
    mon_host = 172.16.74.25,172.16.74.100,172.16.74.101
    auth_cluster_required = none
    auth_service_required = none
    auth_client_required = none
    rbd_cache = false

    [client.radosgw.gateway]
    host =ceph_deploy
    log file = /var/log/ceph/client.radosgw.gateway.log
    rgw_frontends =civetweb port=80
    rgw dns name = ceph_deploy
    rgw print continue = false
  ceph.client.admin.keyring: |-
    [client.admin]
            key = AQDVVvFZ6HN1IRAA7PKrhcaFi5p+PfkEPk8GUw==