apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: node-exporter
  labels:
    app: node-exporter
  namespace: kube-system
spec:
  template:
    metadata:
      labels:
        app: node-exporter
      name: node-exporter
    spec:
      containers:
      - image: hub.chinacloud.com/prometheus/node-exporter:v0.15.2
        resources:
          limits:
            cpu: 100m
            memory: 256Mi
          requests:
            cpu: 100m
            memory: 256Mi
        args:
          - "--web.listen-address=:9110"
          - "--collector.nfs"
          - "--collector.ksmd"
          - "--collector.mountstats"
          - "--collector.systemd"
          - "--collector.tcpstat"
        name: node-exporter
        ports:
        - containerPort: 9110
          hostPort: 9110
          name: scrape
      hostNetwork: true
      hostPID: true