apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: hello-vol
  namespace: default
  labels:
    app: hello-vol
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: hello-vol
    spec:
      terminationGracePeriodSeconds: 60 
      containers:
      - name: hello-vol
        image: docker.io/dockercloud/hello-world:latest
        imagePullPolicy: IfNotPresent
        env:
          - name: PROFILE
            value: "test"
        ports:
          - name: http
            containerPort: 80
        volumeMounts:
          - name: rbd-pvc
            mountPath: "/mnt"
      volumes:
        - name: rbd-pvc
          persistentVolumeClaim:
            claimName: claim1
