apiVersion: v1
kind: Secret
metadata:
  name: ceph-admin-secret2
  namespace: kube-system
type: "kubernetes.io/rbd"
data:
  # ceph auth get-key client.admin | base64
  key: QVFEL052QlpzVkZVRmhBQWtYUmtjMS8rcDJGRG0wajhHdUFKNGc9PQ==
---
apiVersion: v1
kind: Secret
metadata:
  name: ceph-secret2
type: "kubernetes.io/rbd"
data:
  # ceph auth add client.kube mon 'allow r' osd 'allow rwx pool=kube'
  # ceph auth get-key client.kube | base64
  #key: QVFCcDFIVlgrSnBjTXhBQUE4cldVSkRyNEF2cUwvZTZmZ2NRM0E9PQ==
  key: QVFEL052QlpzVkZVRmhBQWtYUmtjMS8rcDJGRG0wajhHdUFKNGc9PQ==
