apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: sleep1
  namespace: default
  labels:
    app: sleep1
  annotations:
    sidecar.istio.io/inject: "false"
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: sleep1
    spec:
      containers:
      - name: sleep1
        image: hub.chinacloud.com/library/curl:latest
        args:
        - sleep
        - "999999"
        imagePullPolicy: IfNotPresent
        ports:
          - name: http
            containerPort: 80
