apiVersion: config.istio.io/v1alpha2
kind: RouteRule
metadata:
  name: demo-default
spec:
  destination:
    name: demo-svc
  precedence: 1
  route:
  - labels:
      version: v1
    weight: 50
  - labels:
      version: v2
    weight: 50
