kind: Service
apiVersion: v1
metadata:
  name: mir-admin-ui-svc
  namespace: fast-mir
  labels:
    app: mir-admin-ui-svc
spec:
  ports:
    - name: mir-admin-ui
      port: 80
      targetPort: 80
      nodePort: 30210
  selector:
      app: mir-admin-ui
  type: NodePort