apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mir-image-builder-api-deployment
  labels:
   app: mir-image-builder-api-deployment
  namespace: fast-mir
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mir-image-builder-api
  template:
    metadata:
      labels:
        app: mir-image-builder-api
    spec:
      containers:
      - name: mir-image-builder-api
        image: hub.chinacloud.com/fast-mir/milestone-mir-image-builder-api:20180418
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 50
          periodSeconds: 30
          timeoutSeconds: 10
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: mir-image-builder-api-conf
          mountPath: /apps/mir-image-builder-api.conf
          subPath: mir-conf.conf
      - name: dind
        image: hub.chinacloud.com/fast-mir/docker:dind
        args: ["--insecure-registry=hub.chinacloud.com"]
        securityContext:
          privileged: true
      volumes:
      - name: mir-image-builder-api-conf
        configMap:
          name: mir-conf-cm
