apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mir-image-api-deployment
  labels:
   app: mir-image-api-deployment
  namespace: fast-mir
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mir-image-api
  template:
    metadata:
      labels:
        app: mir-image-api
    spec:
      containers:
      - name: mir-image-api
        image: hub.chinacloud.com/fast-mir/milestone-mir-image-api:20180418
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 50
          periodSeconds: 30
          timeoutSeconds: 10
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: mir-image-api-conf
          mountPath: /apps/mir-image-api.conf
          subPath: mir-conf.conf
      volumes:
        - name: mir-image-api-conf
          configMap:
            name: mir-conf-cm
