apiVersion: v1
data:
  mir-image-api.yml: |
    #文件上传的大小和格式限制
    file:
      imageRegistry:
        icon:
          size: 5242880
          format: jpg,jpeg,png,bmp,gif
        package:
          size: 1073741824
          format: tar

    #数据库相关信息
    spring:
      datasource:
        url: jdbc:mysql://mysql-svc.fast-common:3306/fast_mir_image?serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&useCursorFetch=true&defaultFetchSize=100
        username: image
        password: 123456
        driver-class-name: com.mysql.jdbc.Driver
        tomcat:
          max-wait: 10000
          max-active: ${parent.datasource.max-active}
          test-on-borrow: true
          initial-size: ${parent.datasource.initial-size}
          validation-query: SELECT 1
          remove-abandoned: ${parent.datasource.remove-abandoned}
          remove-abandoned-timeout: ${parent.datasource.remove-abandoned-timeout}
          min-evictable-idle-time-millis: ${parent.datasource.min-evictable-idle-time-millis}
          time-between-eviction-runs-millis: ${parent.datasource.time-between-eviction-runs-millis}
      jpa:
        show-sql: false
        hibernate:
         # ddl-auto: none
          ddl-auto: none
      jackson:
        serialization:
          indent_output: true


kind: ConfigMap
metadata:
  name: mir-image-api-yml-cm
  namespace: fast-onex
