apiVersion: v1
data:
  mir-application-api.yml: |
    #数据库相关信息
    spring:
      datasource:
        url: jdbc:mysql://mysql-svc.fast-common:3306/fast_mir_application?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&useCursorFetch=true&defaultFetchSize=100
        username: application
        password: 123456
        driver-class-name: com.mysql.jdbc.Driver
        tomcat:
          max-wait: 10000
          max-active: ${parent.datasource.max-active}
          test-on-borrow: true
          initial-size: ${parent.datasource.initial-size}
          validation-query: SELECT 1
          remove-abandoned: ${parent.datasource.remove-abandoned}
          remove-abandoned-timeout: ${parent.datasource.remove-abandoned-timeout}
          min-evictable-idle-time-millis: ${parent.datasource.min-evictable-idle-time-millis}
          time-between-eviction-runs-millis: ${parent.datasource.time-between-eviction-runs-millis}
      jpa:
        show-sql: false
        hibernate:
          ddl-auto: none
      jackson:
        serialization:
          indent_output: true
      cloud:
        loadbalancer:
          retry:
            enabled: true
            
    monitor:
      prometheus:
        url: http://172.16.74.151:30000
        alarminterval: 15
        
    hystrix:
      command:
        default:
          execution:
            isolation:
              thread:
                timeoutInMilliseconds: 60000 #缺省为1000
                
    ribbon:
      ReadTimeout: 60000
      ConnectTimeout: 60000 
    app:
      port:
        start: 30300
        end: 32767
    pod:
      logingTimeOut: 60  #单位是秒
    istio:
      system:
        used:
          cpu: 300 #m
          memory: 512 #mb


kind: ConfigMap
metadata:
  name: mir-application-api-yml-cm
  namespace: fast-onex