apiVersion: v1
data:
  mir-namespace-api.yml: |
    #数据库相关信息
    spring:
      datasource:
        url: jdbc:mysql://mysql-svc.fast-common:3306/fast_mir_namespace?autoReconnect=true&createDatabaseIfNotExist=true&characterEncoding=UTF-8
        username: namespace
        password: 123456
        driver-class-name: com.mysql.jdbc.Driver
        tomcat:
          max-wait: 10000
          max-active: ${parent.datasource.max-active}
          test-on-borrow: true
          initial-size: ${parent.datasource.initial-size}
          validation-query: SELECT 1
          remove-abandoned: ${parent.datasource.remove-abandoned}
          remove-abandoned-timeout: ${parent.datasource.remove-abandoned-timeout}
          min-evictable-idle-time-millis: ${parent.datasource.min-evictable-idle-time-millis}
          time-between-eviction-runs-millis: ${parent.datasource.time-between-eviction-runs-millis}
      jpa:
        database-platform: org.hibernate.dialect.MySQL5Dialect
        hibernate:
          ddl-auto: none
        show-sql: false
kind: ConfigMap
metadata:
  name: mir-namespace-api-yml-cm
  namespace: fast-onex
