apiVersion: v1
data:
  mir-image-builder-api.yml: |
    image:
      builder:
        server: http://localhost:2375
        timeout: 600
    file:
      downloader: http://one-oss-api-svc.fast-onex:8080/api/v1/files/

    #日志配置
    logging:
      level:
        ROOT: INFO
        org.springframework.web: INFO

    #数据库配置    
    spring:
      datasource:
        platform: mysql
        url: jdbc:mysql://mysql-svc.fast-common:3306/fast_mir_image_builder?serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&useCursorFetch=true&defaultFetchSize=100
        username: builder
        password: 123456
        tomcat:
          max-wait: 10000
          max-active: ${parent.datasource.max-active}
          test-on-borrow: true
          initial-size: ${parent.datasource.initial-size}
          validation-query: SELECT 1
          remove-abandoned: ${parent.datasource.remove-abandoned}
          remove-abandoned-timeout: ${parent.datasource.remove-abandoned-timeout}
          min-evictable-idle-time-millis: ${parent.datasource.min-evictable-idle-time-millis}
          time-between-eviction-runs-millis: ${parent.datasource.time-between-eviction-runs-millis}
        driver-class-name: com.mysql.jdbc.Driver
      jpa:
        database-platform: org.hibernate.dialect.MySQL5Dialect
        hibernate:
          ddl-auto: none
        show-sql: false
kind: ConfigMap
metadata:
  name: mir-image-builder-api-yml-cm
  namespace: fast-onex
