apiVersion: v1
data:
  mir-blueprint-api.yml: |
    #日志配置
    logging:
      level:
        ROOT: INFO
        org.springframework.web: INFO

    #数据库相关信息
    spring:
      datasource:
        url: jdbc:mysql://mysql-svc.fast-common:3306/fast_mir_blueprint?autoReconnect=true&createDatabaseIfNotExist=true&characterEncoding=UTF-8
        username: blueprint
        password: 123456
        driver-class-name: com.mysql.jdbc.Driver
        tomcat:
          max-wait: 10000
          max-active: ${parent.datasource.max-active}
          test-on-borrow: true
          initial-size: ${parent.datasource.initial-size}
          validation-query: SELECT 1
          remove-abandoned: ${parent.datasource.remove-abandoned}
          remove-abandoned-timeout: ${parent.datasource.remove-abandoned-timeout}
          min-evictable-idle-time-millis: ${parent.datasource.min-evictable-idle-time-millis}
          time-between-eviction-runs-millis: ${parent.datasource.time-between-eviction-runs-millis}
      jpa:
        show-sql: true
        hibernate:
          ddl-auto: none
      jackson:
        serialization:
          indent_output: true

kind: ConfigMap
metadata:
  name: mir-blueprint-api-yml-cm
  namespace: fast-onex
