apiVersion: v1
data:
  mir-k8s-api.yml: |
    #日志配置
    logging:
      level:
        ROOT: INFO
        org.springframework.web: INFO

    #数据库相关信息
    spring:
      datasource:
        url: jdbc:mysql://mysql-svc.fast-common:3306/fast_mir_k8s?serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&useCursorFetch=true&defaultFetchSize=100
        username: k8s
        password: 123456
        driver-class-name: com.mysql.jdbc.Driver
        tomcat:
          max-wait: 10000
          max-active: ${parent.datasource.max-active}
          test-on-borrow: true
          initial-size: ${parent.datasource.initial-size}
          validation-query: SELECT 1
          remove-abandoned: ${parent.datasource.remove-abandoned}
          remove-abandoned-timeout: ${parent.datasource.remove-abandoned-timeout}
          min-evictable-idle-time-millis: ${parent.datasource.min-evictable-idle-time-millis}
          time-between-eviction-runs-millis: ${parent.datasource.time-between-eviction-runs-millis}
      jpa:
        database-platform: org.hibernate.dialect.MySQL5Dialect
        hibernate:
          ddl-auto: none
        show-sql: false


      jackson:
        serialization:
          indent_output: true

    k8s:
      app:
        domain: fast
      fast:
        domain: fast-basic
    monitor:
      prometheus:
        kubernetesServer: http://172.16.74.151:8080
        namespace: kube-system
        configMap: alert-rules-templates


kind: ConfigMap
metadata:
  name: mir-k8s-api-yml-cm
  namespace: fast-onex
