apiVersion: v1
data:
  one-oss-api.yml: |
    #上传的文件根路径&fast默认图标的地址
    upload:
      path: /opt/server/one-oss/fileUpload
      fast:
        default:
          icon:
            path: /opt/server/one-oss/fast/default/icon

    #数据库相关信息
    spring:
      datasource:
        url: jdbc:mysql://mysql-svc.fast-common/fast_one_oss?autoReconnect=true&createDatabaseIfNotExist=true&characterEncoding=UTF-8
        username: oss
        password: 123456
        driver-class-name: com.mysql.jdbc.Driver
        tomcat:
          max-wait: 10000
          max-active: ${parent.datasource.max-active}
          test-on-borrow: true
          initial-size: ${parent.datasource.initial-size}
          validation-query: SELECT 1
          remove-abandoned: ${parent.datasource.remove-abandoned}
          remove-abandoned-timeout: ${parent.datasource.remove-abandoned-timeout}
          min-evictable-idle-time-millis: ${parent.datasource.min-evictable-idle-time-millis}
          time-between-eviction-runs-millis: ${parent.datasource.time-between-eviction-runs-millis}
      jpa:
        properties:
          hibernate:
            hbm2ddl:
              auto: none

kind: ConfigMap
metadata:
  name: one-oss-api-yml-cm
  namespace: fast-onex
