---
kind: ConfigMap
apiVersion: v1
metadata:
  name: alertmanager-conf
  labels:
    name: alertmanager-conf
  namespace: kube-system
data:
  config.yml: |
    global:
      resolve_timeout: 5m
      smtp_smarthost: 'mail.com:25'
      smtp_from: 'mail@mail.com'
      smtp_auth_username: 'mail'
      smtp_auth_password: 'mail'
      slack_api_url: '<slack_api_url>'
    templates:
    - '/etc/alertmanager/templates/*.html'
    route:
      group_by: ['alertname', 'cluster', 'service']
      group_wait: 30s
      group_interval: 5m
      repeat_interval: 15m
      receiver: slack-notifications
      routes:
      - match:
          severity: files
        receiver: email_alert
      - match:
          severity: critical
        receiver: send-to-fast
    receivers:
    - name: 'send-to-fast'
      webhook_configs:
      - url:   http://127.0.0.1:8080/fast/alarmscall/host
    - name: 'email_alert'
      email_configs:
      - to: 'user@yourcompany.com'
    - name: 'slack-notifications'
      slack_configs:
      - channel: '#alerts'