apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: datadir-zookeeper-0
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  selector:
    matchLabels:
      app: zookeeper
      podindex: "0"

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: datadir-zookeeper-1
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  selector:
    matchLabels:
      app: zookeeper
      podindex: "1"

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: datadir-zookeeper-2
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  selector:
    matchLabels:
      app: zookeeper
      podindex: "2"
