apiVersion: v1
kind: PersistentVolume
metadata:
  name: datadir-zkcluster-0
  labels:
    app: zookeeper
    podindex: "0"
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 50Gi
  nfs:
    path: "/home/nfs/zk/zkcluster1"
    server: 172.16.74.101
    readOnly: false
  persistentVolumeReclaimPolicy: Recycle

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: datadir-zkcluster-1
  labels:
    app: zookeeper
    podindex: "1"
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 50Gi
  nfs:
    path: "/home/nfs/zk/zkcluster2"
    server: 172.16.74.101
    readOnly: false
  persistentVolumeReclaimPolicy: Recycle

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: datadir-zkcluster-2
  labels:
    app: zookeeper
    podindex: "2"
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 50Gi
  nfs:
    path: "/home/nfs/zk/zkcluster3"
    server: 172.16.74.101
    readOnly: false
  persistentVolumeReclaimPolicy: Recycle
