apiVersion: v1
kind: PersistentVolume
metadata:
  name: datadir-galera-0
  labels:
    app: galera-ss
    podindex: "0"
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 100Gi
  rbd:
    monitors:
      - 172.16.71.109:6789
      - 172.16.71.110:6789
      - 172.16.71.111:6789
    pool: images-vol
    user: admin
    image: ceph-image04
    secretRef:
      name: ceph-secret
    fsType: ext4
    readOnly: false
  persistentVolumeReclaimPolicy: Recycle


---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: datadir-galera-1
  labels:
    app: galera-ss
    podindex: "1"
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 100Gi
  rbd:
    monitors:
      - 172.16.71.109:6789
      - 172.16.71.110:6789
      - 172.16.71.111:6789
    pool: images-vol
    user: admin
    image: ceph-image02
    secretRef:
      name: ceph-secret
    fsType: ext4
    readOnly: false
  persistentVolumeReclaimPolicy: Recycle

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: datadir-galera-2
  labels:
    app: galera-ss
    podindex: "2"
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 100Gi
  rbd:
    monitors:
      - 172.16.71.109:6789
      - 172.16.71.110:6789
      - 172.16.71.111:6789
    pool: images-vol
    user: admin
    image: ceph-image03
    secretRef:
      name: ceph-secret
    fsType: ext4
    readOnly: false
  persistentVolumeReclaimPolicy: Recycle
