apiVersion: v1
kind: PersistentVolume
metadata:
  name: datadir-kfcluster-0
  labels:
    app: kafka
    podindex: "0"
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 50Gi
  rbd:
    monitors:
      - 172.16.74.25:6789
      - 172.16.74.100:6789
      - 172.16.74.101:6789
    pool: kube
    user: admin
    image: kafka-01
    secretRef:
      name: ceph-secret
    fsType: ext4
    readOnly: false
  persistentVolumeReclaimPolicy: Recycle

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: datadir-kfcluster-1
  labels:
    app: kafka
    podindex: "1"
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 50Gi
  rbd:
    monitors:
      - 172.16.74.25:6789
      - 172.16.74.100:6789
      - 172.16.74.101:6789
    pool: kube
    user: admin
    image: kafka-02
    secretRef:
      name: ceph-secret
    fsType: ext4
    readOnly: false
  persistentVolumeReclaimPolicy: Recycle

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: datadir-kfcluster-2
  labels:
    app: kafka
    podindex: "2"
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 50Gi
  rbd:
    monitors:
      - 172.16.74.25:6789
      - 172.16.74.100:6789
      - 172.16.74.101:6789
    pool: kube
    user: admin
    image: kafka-03
    secretRef:
      name: ceph-secret
    fsType: ext4
    readOnly: false
  persistentVolumeReclaimPolicy: Recycle
