apiVersion: v1
kind: Secret
metadata:
  name: ceph-admin-secret-71
type: "kubernetes.io/rbd"  
data:
  # ceph auth get-key client.admin | base64
  key: QVFEL052QlpzVkZVRmhBQWtYUmtjMS8rcDJGRG0wajhHdUFKNGc9PQ==

---
apiVersion: v1
kind: Secret
metadata:
  name: ceph-secret-71
type: "kubernetes.io/rbd"
data:
  # ceph auth add client.kube mon 'allow r' osd 'allow rwx pool=kube'
  # ceph auth get-key client.kube | base64
  key: QVFBcThUMWFGL24xTnhBQUxSSlltd3BsUkxZQWRsSWZ0UllGY0E9PQ==
