apiVersion: v1
kind: PersistentVolume
metadata:
  name: datadir-escluster-0
  labels:
    app: elasticsearch-ss
    podindex: "0"
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 100Gi
  rbd:
    monitors:
      - 172.16.71.109:6789
      - 172.16.71.110:6789
      - 172.16.71.111:6789
    pool: kube
    user: kube
    image: es-image01
    secretRef:
      name: ceph-secret-71
    fsType: ext4
    readOnly: false
  persistentVolumeReclaimPolicy: Recycle

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: datadir-escluster-1
  labels:
    app: elasticsearch-ss
    podindex: "1"
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 100Gi
  rbd:
    monitors:
      - 172.16.71.109:6789
      - 172.16.71.110:6789
      - 172.16.71.111:6789
    pool: kube
    image: es-image02
    user: kube
    secretRef:
      name: ceph-secret-71
    fsType: ext4
    readOnly: false
  persistentVolumeReclaimPolicy: Recycle

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: datadir-escluster-2
  labels:
    app: elasticsearch-ss
    podindex: "2"
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 100Gi
  rbd:
    monitors:
      - 172.16.71.109:6789
      - 172.16.71.110:6789
      - 172.16.71.111:6789
    pool: kube
    image: es-image03
    user: kube
    secretRef:
      name: ceph-secret-71
    fsType: ext4
    readOnly: false
  persistentVolumeReclaimPolicy: Recycle
