apiVersion: v1
kind: LimitRange
metadata:
  name: mylimits
  namespace: development  
spec:
  limits:
  - max:
      cpu: "2"
      memory: 2Gi
    min:
      cpu: 200m
      memory: 6Mi
    type: Pod
  - default:
      cpu: 300m
      memory: 200Mi
    defaultRequest:
      cpu: 200m
      memory: 10Mi
    max:
      cpu: "1"
      memory: 1Gi
    min:
      cpu: 100m
      memory: 3Mi
    type: Container
