apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: nginx-base
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: www.chinacloud.com
    http:
      paths:
      - path: /demo
        backend:
          serviceName: demo-svc
          servicePort: 80
