apiVersion: v1
kind: Service
metadata:
  name: galera-ss
  labels:
    app: galera-ss
spec:
  type: NodePort
  ports:
    - nodePort: 19508
      port: 3306
      name: mysql
#  clusterIP: None
  selector:
    app: galera-ss

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: galera-ss
  labels:
    app: galera-ss
  annotations:
    sidecar.istio.io/inject: "false"
spec:
  serviceName: "galera-ss"
  replicas: 3
  selector:
    matchLabels:
      app: galera-ss
  template:
    metadata:
      labels:
        app: galera-ss
    spec:
      containers:
      - name: galera
        image: hub.chinacloud.com/catalog/mariadb:10.1.28
        ports:
        - name: mysql
          containerPort: 3306
        env:
        # kubectl create secret generic mysql-pass --from-file=password.txt
        - name: MYSQL_ROOT_PASSWORD
          value: chunacloudroot
        - name: DISCOVERY_SERVICE
          value: etcd-client:2379
        - name: XTRABACKUP_PASSWORD
          value: chunacloud
        - name: CLUSTER_NAME
          value: mariadb_galera_ss
        - name: MYSQL_DATABASE
          value: chinacloud
        - name: MYSQL_USER
          value: chinacloud
        - name: MYSQL_PASSWORD
          value: chinacloudpw
        readinessProbe:
          exec:
            command:
            - /healthcheck.sh
            - --readiness
          initialDelaySeconds: 120
          periodSeconds: 1
        livenessProbe:
          exec:
            command:
            - /healthcheck.sh
            - --liveness
          initialDelaySeconds: 120
          periodSeconds: 1
        volumeMounts:
        - name: mysql-datadir
          mountPath: /var/lib/mysql
  volumeClaimTemplates:
  - metadata:
      name: mysql-datadir
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 100Gi
