apiVersion: v1
kind: PersistentVolume
metadata:
  name: datadir-zkcluster-0
  labels:
    app: zookeeper
    podindex: "0"
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 50Gi
  rbd:
    monitors:
      - 172.16.74.25:6789
      - 172.16.74.100:6789
      - 172.16.74.101:6789
    pool: kube
    user: admin
    image: zookeeper-04
    secretRef:
      name: ceph-secret
    fsType: ext4
    readOnly: false
  persistentVolumeReclaimPolicy: Recycle

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: datadir-zkcluster-1
  labels:
    app: zookeeper
    podindex: "1"
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 50Gi
  rbd:
    monitors:
      - 172.16.74.25:6789
      - 172.16.74.100:6789
      - 172.16.74.101:6789
    pool: kube
    user: admin
    image: zookeeper-05
    secretRef:
      name: ceph-secret
    fsType: ext4
    readOnly: false
  persistentVolumeReclaimPolicy: Recycle

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: datadir-zkcluster-2
  labels:
    app: zookeeper
    podindex: "2"
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 50Gi
  rbd:
    monitors:
      - 172.16.74.25:6789
      - 172.16.74.100:6789
      - 172.16.74.101:6789
    pool: kube
    user: admin
    image: zookeeper-06
    secretRef:
      name: ceph-secret
    fsType: ext4
    readOnly: false
  persistentVolumeReclaimPolicy: Recycle
