---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: elasticsearch-ss
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: elasticsearch-ss
rules:
- apiGroups:
  - ""
  resources:
  - endpoints
  verbs:
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: elasticsearch-ss
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: elasticsearch-ss
subjects:
- kind: ServiceAccount
  name: elasticsearch-ss
  namespace: default
---
apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-ss
  labels:
    app: elasticsearch-ss
spec:
  type: NodePort
  selector:
    app: elasticsearch-ss
  ports:
  - name: http
    port: 9200
    protocol: TCP
    nodePort: 19500
  - name: transport
    port: 9300
---
apiVersion: apps/v1beta2
kind: StatefulSet
metadata:
  name: elasticsearch-ss
  labels:
    app: elasticsearch-ss
  annotations:
    sidecar.istio.io/inject: "false"
spec:
  serviceName: elasticsearch-ss
  replicas: 3
  selector:
    matchLabels:
      app: elasticsearch-ss
  template:
    metadata:
      labels:
        app: elasticsearch-ss
    spec:
      serviceAccount: elasticsearch-ss
      initContainers:
      - name: init-sysctl
        image: hub.chinacloud.com/efk/alpine:3.6
        imagePullPolicy: IfNotPresent
        command: ["sysctl", "-w", "vm.max_map_count=262144"]
        securityContext:
          privileged: true
      containers:
      - name: elasticsearch-ss
        resources:
          # need more cpu upon initialization, therefore burstable class
          limits:
            cpu: 1000m
          requests:
            cpu: 100m
        securityContext:
          capabilities:
            add:
              - IPC_LOCK
        image: hub.chinacloud.com/catalog/elasticsearch-k8s:5.6.4
        env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: "CLUSTER_NAME"
          value: "myesdb"
        - name: "DISCOVERY_SERVICE"
          value: "elasticsearch-ss"
        - name: NODE_MASTER
          value: "true"
        - name: NODE_DATA
          value: "true"
        - name: HTTP_ENABLE
          value: "true"
        - name: NUMBER_OF_MASTERS
          value: "3"
        ports:
        - containerPort: 9200
          name: http
          protocol: TCP
        - containerPort: 9300
          name: transport
          protocol: TCP
        volumeMounts:
        - mountPath: /data
          name: es-datadir
  volumeClaimTemplates:
  - metadata:
      name: es-datadir
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 100Gi
