apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: datadir-kafka-0
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  selector:
    matchLabels:
      app: kafka
      podindex: "0"

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: datadir-kafka-1
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  selector:
    matchLabels:
      app: kafka
      podindex: "1"

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: datadir-kafka-2
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  selector:
    matchLabels:
      app: kafka
      podindex: "2"
