apiVersion: v1
kind: PersistentVolume
metadata:
  name: datadir-kfcluster-0
  labels:
    app: kafka
    podindex: "0"
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 50Gi
  nfs:
    path: "/home/nfs/kfk/kfkcluster1"
    server: 172.16.74.101
    readOnly: false 
  persistentVolumeReclaimPolicy: Recycle

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: datadir-kfcluster-1
  labels:
    app: kafka
    podindex: "1"
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 50Gi
  nfs:
    path: "/home/nfs/kfk/kfkcluster2"
    server: 172.16.74.101
    readOnly: false 
  persistentVolumeReclaimPolicy: Recycle

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: datadir-kfcluster-2
  labels:
    app: kafka
    podindex: "2"
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 50Gi
  nfs:
    path: "/home/nfs/kfk/kfkcluster3"
    server: 172.16.74.101
    readOnly: false 
  persistentVolumeReclaimPolicy: Recycle
