---
kind: Service
apiVersion: v1
metadata:
  name: outside-0
  namespace: default
spec:
  selector:
    app: kafka
    kafka-broker-id: "0"
  ports:
  - protocol: TCP
    targetPort: 9094
    port: 19509
    nodePort: 19509
  type: NodePort

---
kind: Service
apiVersion: v1
metadata:
  name: outside-1
  namespace: default
spec:
  selector:
    app: kafka
    kafka-broker-id: "1"
  ports:
  - protocol: TCP
    targetPort: 9094
    port: 19510
    nodePort: 19510
  type: NodePort

---
kind: Service
apiVersion: v1
metadata:
  name: outside-2
  namespace: default
spec:
  selector:
    app: kafka
    kafka-broker-id: "2"
  ports:
  - protocol: TCP
    targetPort: 9094
    port: 19511
    nodePort: 19511
  type: NodePort
