apiVersion: "etcd.database.coreos.com/v1beta2"
kind: "EtcdCluster"
metadata:
  name: "example-etcd-cluster"
spec:
  size: 3
  repository: "hub.chinacloud.com/catalog/etcd"
  version: "3.2.13"
  pod:
    busyboxImage: "hub.chinacloud.com/common/busybox:1.28.0-glibc"
