kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: rbd-demo
provisioner: ceph.com/rbd
parameters:
  monitors: 172.16.74.141:6789
  pool: kube
  adminId: admin
  adminSecretNamespace: kube-system
  adminSecretName: ceph-admin-secret
  userId: kube
  userSecretName: ceph-secret
  imageFormat: "2"
  imageFeatures: layering
