apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: helloworld-mnt-rbd
  namespace: default
  labels:
    app: helloworld-mnt-rbd
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: helloworld-mnt-rbd
    spec:
      terminationGracePeriodSeconds: 60 
      containers:
      - name: helloworld-mnt-rbd
        image: hub.chinacloud.com/library/hello-world:1.0
        imagePullPolicy: IfNotPresent
        env:
          - name: PROFILE
            value: "test"
        ports:
          - name: http
            containerPort: 80
        volumeMounts:
          - name: rbd-pvc
            mountPath: "/mnt"
      volumes:
        - name: rbd-pvc
          persistentVolumeClaim:
            claimName: helloworld-claim-demo
