apiVersion: v1
kind: Service
metadata:
  name: keycloak-svc
  namespace: fast-common
  labels:
    app: keycloak
spec:
  ports:
  - port: 8080
    nodePort: 30200
    targetPort: 8080
  type: NodePort 
  selector:
    app: keycloak