apiVersion: v1
kind: Service
metadata:
  name: mysql-svc
  namespace: fast-common
  labels:
    app: mysql
spec:
  ports:
  - port: 3306
    nodePort: 30201
    targetPort: 3306
  type: NodePort 
  selector:
    app: mysql