apiVersion: v1
kind: Service
metadata:
  name: postgres-svc
  namespace: fast-common
  labels:
    app: postgres
spec:
  ports:
  - port: 5432
    nodePort: 30202
    targetPort: 5432
  type: NodePort 
  selector:
    app: postgres