apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: rabbitmq-deployment
  labels:
    app: rabbitmq
  namespace: fast-common
spec:
  replicas: 1
  selector:
    matchLabels:
     app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
        - name: rabbitmq
          image: hub.chinacloud.com/fast-common/rabbitmq:3.6.14-management
          imagePullPolicy: Always
          ports:
            - name: rabbitmq
              containerPort: 15672
              protocol: TCP
            - name: rabbitmq1
              containerPort: 5672
              protocol: TCP
          imagePullPolicy: "IfNotPresent"
          livenessProbe:
            tcpSocket:
              port: 5672
            initialDelaySeconds: 50
            periodSeconds: 30
          volumeMounts:
            - name: rabbitmq
              mountPath: /var/lib/rabbitmq
          env:
            - name: "RABBITMQ_DEFAULT_USER"
              value: "fast"
            - name: "RABBITMQ_DEFAULT_PASS"
              value: "fast"
            - name: "RABBITMQ_DEFAULT_VHOST"
              value: "/"
            - name: "hostname"
              value: "fast-rabbit"
          # resources:
          #   limits:
          #     memory: 512Mi
          #   requests:
          #     memory: 256Mi
      volumes:
        - name: rabbitmq
          persistentVolumeClaim:
            claimName: rabbitmq-pvc