apiVersion: v1
kind: Service
metadata:
  name: zookeeper-svc
  namespace: fast-common
  labels:
    app: zookeeper
spec:
  ports:
  - port: 2181
    nodePort: 30205
    targetPort: 2181
  type: NodePort 
  selector:
    app: zookeeper